---

# all
# ansible_vmware_validate_certs: no
#ansible_connection: vmware_tools
ansible_connection: ssh
# ansible_vmware_guest_path: "DC1/vm/"
# vcenter_hostname: "{{ lookup('env','VMWARE_HOST') }}"
# vcenter_username: "{{ lookup('env','VMWARE_USER') }}"
# vcenter_password: "{{ lookup('env','VMWARE_PASSWORD') }}"

# rhel
rhel_vm: rhel-1
rh_subs_pool_id: 8a85f99c7d76f2fd017d96c343f40655
